version: 
services:
  web:
    build:
      context: ./velosport
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./velosport:/app
    environment:
      - FLASK_ENV=development
