
services:
  web:
    build:
      context: .
      dockerfile: /velosport/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./velosport:/app
    environment:
      - FLASK_ENV=development
      - SCRIPT=app.py  

  parser:
    build:
      context: ./velosport
      dockerfile: Dockerfile
    volumes:
      - ./velosport:/app
    environment:
      - SCRIPT=parser.py  
