services:
  parser:
    build:
      context: ./velosport
      dockerfile: Dockerfile
    volumes:
      - ./velosport:/app
    command: ["python", "parser.py"]

  web:
    build:
      context: ./velosport
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./velosport:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - parser
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
